//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_3
    {
        public int Bid { get; set; }
        public string Bname { get; set; }
        public string author { get; set; }
        public string publisher { get; set; }
        public Nullable<System.DateTime> issued { get; set; }
        public Nullable<System.DateTime> returned { get; set; }
    }
}
